### ISSUE TITLE
:octocat: auto [lint,test,build] code when PR

### ISSUE THREAD

**Issue by nnnnusui** [nnnnusui/youtube_immersive#5]
自動コードチェックworkflowを書く

**Comment by nnnnusui** [comment]
[再利用可能なworkflow](https://docs.github.com/ja/actions/using-workflows/reusing-workflows#example-reusable-workflow)として[devcontainerの立ち上げ](https://github.com/devcontainers/ci/blob/main/docs/github-action.md#other-examples)を行おうと考えたが、
ghcr.ioに予めコンテナ用リポジトリを作っておく必要がある感じみたいなので、やめよっかなーになっている。

下記はghcr.ioにコンテナをバックアップするCallableWorkflowの例。

```yaml
// pre-build.yml
name: pre-build

on:
  workflow_call

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}_devcontainer
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}_devcontainer
          push: always
```

使用側はこう。

```yaml
name: code-check

on:
  push

jobs:
  pre-build:
    uses: ./.github/workflows/pre-build.yml
    secrets: inherit
  code-check:
    needs: [pre-build]
    runs-on: ubuntu-latest
    steps:
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}_devcontainer
          runCmd: |
            pnpm lint
            pnpm test
            pnpm build
```
